name: setup-fvm
description: An action installs and caches FVM, Flutter SDK, and dependencies using FVM.
author: cq
branding:
  color: blue
  icon: arrow-down-circle

inputs:
  working-directory:
    description: The root directory of the Flutter project.
    required: false
    default: "."

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js
