name: setup-fvm
description: An action installs and caches FVM, Flutter SDK, and dependencies using FVM.
author: cq
branding:
  color: blue
  icon: arrow-down-circle

inputs:
  project-dir:
    description: Path to the Flutter project root.
    required: false
    default: "."
  cache:
    description: Whether to cache Flutter SDK and Pub packages (in ~/.pub-cache).
    required: false
    default: "true"

outputs:
  flutter-cache-hit:
    description: The key for the cache hit of Flutter SDK cache.
  pub-cache-hit:
    description: The key for the cache hit if Pub packages cache.

runs:
  using: node24
  main: dist/main.js
  post: dist/post.js
